packages:
  - "apps/*"
  - "packages/*"
  - "tests/*"

onlyBuiltDependencies:
  - "@prisma/client"
  - "@prisma/engines"
  - "@prisma/query-engine-wasm"
  - "bcrypt"
  - "esbuild"
  - "prisma"
  - "sharp"
  - "unrs-resolver"
